# Generated by Django 6.1.1 on 2026-09-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('pessoa_emprestada', models.CharField(blank=True, max_length=150, null=True)),
                ('esta_emprestado', models.BooleanField(default=False, verbose_name='Está Emprestado?')),
            ],
        ),
    ]
