# Generated by Django 6.1.1 on 2026-09-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebooks',
            new_name='Notebook',
        ),
    ]
